application: php-savio
version: 1
runtime: php55
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /
  script: main.php

- url: /busreis
  script: busreis.php
  
- url: /error
  script: error.php
  
- url: /naam
  script: naam.php
  
- url: /kerstboom
  script: kerstboom.php
  
- url: /While>>For
  script: wnf.php